const listaPalabras = [
  'perro', 'Animal',
  'gato', 'Animal',
  'elefante', 'Animal',
  'mono','Animal',
  'pájaro', 'Animal',
  'cucaracha', 'Animal',
  'java', 'Lenguaje de programación',
  'javascript', 'Lenguaje de programación',
  'iron man', 'Y yo soy... (Frase icónica 2019)',
  'imperfecto', 'Perfectamente...',
  'guns n\' roses', 'Banda de Rock',
  'poker', 'Juego de cartas',
  'apple', 'Marca de móviles',
  'coca cola', 'Refresco',
  'instrucciones', 'Guía sobre algo',
  'creditos', 'Final de una pelicula',
  'iron man', 'Película',
  'star wars', 'Saga de películas',
  'El Señor de Los Anillos', 'Saga de Películas',
  'Transformers', 'Saga de Películas',
  'Harry Potter', 'Película',
  'forest', 'Película',
  'AC/DC', 'Banda de Rock',
  'Kiss', 'Banda de Rock',
  'Metallica', 'Banda de Rock',
  'Led Zepellin', 'Banda de Rock',
  'Bohemian Rhapsody', 'Canción Queen',
  'Rihanna', 'Cantante',
  'David Guetta', 'DJ',
  'American dad', 'Serie',
  'Juego de Tronos', 'Serie',
  'Breaking Bad', 'Serie',
  'Shin Chan', 'Serie de dibujos',
  'Friends', 'Serie'
];
